/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zrb_hellojni_MainActivity */

#ifndef _Included_com_zrb_hellojni_MainActivity
#define _Included_com_zrb_hellojni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zrb_hellojni_MainActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zrb_hellojni_MainActivity_helloJni
  (JNIEnv *env, jclass jcl){
  return env->NewStringUTF("hello jni");
  };

/*
 * Class:     com_zrb_hellojni_MainActivity
 * Method:    addCalc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zrb_hellojni_MainActivity_addCalc
  (JNIEnv *env, jclass jcl, jint a, jint b){
  return a+b;
  };

#ifdef __cplusplus
}
#endif
#endif
